### ISSUE TITLE
LC-113/Path Sum 2 

### ISSUE THREAD

**Issue by zetsubou24** [zetsubou24/Hacktober-ProblemSolving#1]
Given a binary tree and a sum, find all root-to-leaf paths where each path's sum equals the given sum.

Note: A leaf is a node with no children.

https://leetcode.com/problems/path-sum-ii/

**Comment by ankitsri1998** [comment]
Sir please Assign this to me , i can resolve it.
thank you

**Comment by yokaiemporer** [comment]
Hello , can you assign this to me if its unassigned.

**Comment by zetsubou24** [comment]
Closed.
